name: Veracode Build Helper
description: Facilitador de build e empacotamento (.zip) para Veracode, começando por .NET (com parâmetros completos e extensíveis).
author: Bantuu
branding:
  icon: shield
  color: purple

inputs:
  language:
    description: "Linguagem/módulo a usar (por enquanto: dotnet)."
    required: false
    default: "dotnet"
  working_directory:
    description: Diretório base para build e empacotamento.
    required: false
    default: "."

  # dotnet - setup
  dotnet_version:
    description: "Versão do .NET SDK (ex.: 8.0.x). Se vazio, não chama actions/setup-dotnet."
    required: false
    default: ""
  dotnet_version_file:
    description: "Arquivo com versão do SDK (ex.: global.json). Alternativa a dotnet_version."
    required: false
    default: ""

  # dotnet - alvo
  dotnet_project:
    description: "Caminho do .csproj/.fsproj/.vbproj/.sln (relativo ao working_directory). Vazio = diretório atual."
    required: false
    default: ""

  # dotnet - execução
  dotnet_restore:
    description: "Se 'true', executa dotnet restore."
    required: false
    default: "true"
  dotnet_build:
    description: "Se 'true', executa dotnet build."
    required: false
    default: "false"
  dotnet_test:
    description: "Se 'true', executa dotnet test."
    required: false
    default: "false"
  dotnet_publish:
    description: "Se 'true', executa dotnet publish (recomendado para empacotar)."
    required: false
    default: "true"

  # dotnet - parâmetros comuns
  dotnet_configuration:
    description: "Configuration (ex.: Release/Debug)."
    required: false
    default: "Release"
  dotnet_framework:
    description: "TargetFramework (ex.: net8.0)."
    required: false
    default: ""
  dotnet_runtime:
    description: "RID (ex.: win-x64, linux-x64, osx-x64)."
    required: false
    default: ""
  dotnet_self_contained:
    description: "Self-contained publish ('true'/'false')."
    required: false
    default: "false"

  # dotnet - MSBuild first-class
  dotnet_verbosity:
    description: "Verbosity do dotnet (ex.: quiet, minimal, normal, detailed, diagnostic)."
    required: false
    default: ""
  dotnet_nologo:
    description: "Se 'true', passa --nologo."
    required: false
    default: "false"
  dotnet_disable_parallel:
    description: "Se 'true', passa --disable-parallel (quando suportado)."
    required: false
    default: "false"
  dotnet_msbuild_targets:
    description: "Targets MSBuild (ex.: Build;Publish)."
    required: false
    default: ""
  dotnet_msbuild_properties:
    description: "Propriedades MSBuild (multiline). Cada linha pode ser Name=Value ou -p:Name=Value."
    required: false
    default: ""

  # dotnet - publish flags (quando suportados)
  dotnet_publish_single_file:
    description: "PublishSingleFile ('true'/'false')."
    required: false
    default: "false"
  dotnet_publish_trimmed:
    description: "PublishTrimmed ('true'/'false')."
    required: false
    default: "false"
  dotnet_publish_ready_to_run:
    description: "PublishReadyToRun ('true'/'false')."
    required: false
    default: "false"

  # dotnet - override de argumentos (avançado)
  dotnet_restore_args:
    description: "Args extras para dotnet restore."
    required: false
    default: ""
  dotnet_build_args:
    description: "Args extras para dotnet build."
    required: false
    default: ""
  dotnet_test_args:
    description: "Args extras para dotnet test."
    required: false
    default: ""
  dotnet_publish_args:
    description: "Args extras para dotnet publish."
    required: false
    default: ""
  dotnet_publish_dir:
    description: "Diretório de saída do publish (relativo ao working_directory)."
    required: false
    default: "publish"

  # dotnet - multi-projeto (opcional)
  dotnet_publish_multi:
    description: "Se 'true', publica múltiplos projetos em subpastas dentro de dotnet_publish_dir."
    required: false
    default: "false"
  dotnet_projects:
    description: "Lista (multiline) de projetos para publish (paths .csproj). Se vazio e dotnet_project for .sln, usa 'dotnet sln list'."
    required: false
    default: ""
  dotnet_projects_include:
    description: "Filtro include (multiline) para projetos no publish_multi (wildcards). Se vazio, inclui todos."
    required: false
    default: ""
  dotnet_projects_exclude:
    description: "Filtro exclude (multiline) para projetos no publish_multi (wildcards)."
    required: false
    default: ""

  # dotnet - nuget (opcional)
  enable_nuget:
    description: "Se 'true', configura NuGet antes do restore (private feeds). Se vazio, ativa automaticamente quando algum nuget_* for informado."
    required: false
    default: ""
  nuget_auth_mode:
    description: "Modo de autenticação do NuGet: dotnet|setup-dotnet|config. Use setup-dotnet para evitar --store-password-in-clear-text quando possível."
    required: false
    default: "dotnet"
  nuget_config_path:
    description: "Path do nuget.config (relativo ao working_directory) para usar no restore."
    required: false
    default: ""
  nuget_config_content:
    description: "Conteúdo do nuget.config (multiline). Se informado, gera um arquivo temporário e usa no restore."
    required: false
    default: ""
  nuget_source_url:
    description: "URL do feed para adicionar via 'dotnet nuget add source'."
    required: false
    default: ""
  nuget_source_name:
    description: "Nome do source a ser adicionado (default: 'private')."
    required: false
    default: "private"
  nuget_username:
    description: "Username para o source (quando usar auth por username/password)."
    required: false
    default: "token"
  nuget_password:
    description: "Password/token para o source (use secrets)."
    required: false
    default: ""
  nuget_sources:
    description: "Lista (multiline) de sources no formato name|url|username|password (username/password opcionais)."
    required: false
    default: ""
  nuget_sources_json:
    description: "Lista (JSON) de sources (mais seguro que nuget_sources). Ex.: [{\"name\":\"private\",\"url\":\"...\",\"username\":\"token\",\"password\":\"...\"}]"
    required: false
    default: ""
  nuget_locked_mode:
    description: "Se 'true', passa --locked-mode no restore."
    required: false
    default: "false"
  nuget_ignore_failed_sources:
    description: "Se 'true', passa --ignore-failed-sources no restore."
    required: false
    default: "false"
  nuget_interactive:
    description: "Se 'true', passa --interactive no restore."
    required: false
    default: "false"
  nuget_packages_dir:
    description: "Diretório de packages para o restore (--packages)."
    required: false
    default: ""
  nuget_no_cache:
    description: "Se 'true', passa --no-cache no restore."
    required: false
    default: "false"

  # empacotamento
  package_paths:
    description: "Paths/globs para incluir no zip (multiline). Se vazio, usa o default do módulo (ex.: publish/** no dotnet)."
    required: false
    default: ""
  exclude_paths:
    description: "Paths/globs para excluir do zip (multiline)."
    required: false
    default: |
      .git/**
      .github/**
      **/.git/**
      **/.github/**
      **/.DS_Store
      **/node_modules/**
  output_zip:
    description: "Nome do zip gerado (somente filename). A saída é fixa em `veracode/<output_zip>`."
    required: false
    default: "app.zip"
  fail_on_empty_zip:
    description: "Se 'true', falha se nenhum arquivo for empacotado."
    required: false
    default: "true"

outputs:
  zip_path:
    description: Caminho do zip gerado (relativo ao workspace).
    value: ${{ steps.package.outputs.zip_path }}
  zip_bytes:
    description: Tamanho do zip em bytes.
    value: ${{ steps.package.outputs.zip_bytes }}
  zip_files:
    description: Quantidade de arquivos dentro do zip.
    value: ${{ steps.package.outputs.zip_files }}
  build_ran:
    description: "'true'/'false' indicando se o build (dotnet) rodou."
    value: ${{ steps.dotnet.outputs.build_ran }}
  language_effective:
    description: Módulo efetivo usado (ou vazio).
    value: ${{ steps.dotnet.outputs.language_effective }}
  dotnet_publish_dir:
    description: Diretório efetivo do publish (relativo ao working_directory).
    value: ${{ steps.dotnet.outputs.publish_dir }}

runs:
  using: composite
  steps:
    - name: Dotnet build
      id: dotnet
      if: inputs.language == 'dotnet'
      uses: ./internal/dotnet
      with:
        working_directory: ${{ inputs.working_directory }}
        dotnet_version: ${{ inputs.dotnet_version }}
        dotnet_version_file: ${{ inputs.dotnet_version_file }}
        project: ${{ inputs.dotnet_project }}
        enable_nuget: ${{ inputs.enable_nuget }}
        nuget_auth_mode: ${{ inputs.nuget_auth_mode }}
        nuget_config_path: ${{ inputs.nuget_config_path }}
        nuget_config_content: ${{ inputs.nuget_config_content }}
        nuget_source_url: ${{ inputs.nuget_source_url }}
        nuget_source_name: ${{ inputs.nuget_source_name }}
        nuget_username: ${{ inputs.nuget_username }}
        nuget_password: ${{ inputs.nuget_password }}
        nuget_sources: ${{ inputs.nuget_sources }}
        nuget_sources_json: ${{ inputs.nuget_sources_json }}
        nuget_locked_mode: ${{ inputs.nuget_locked_mode }}
        nuget_ignore_failed_sources: ${{ inputs.nuget_ignore_failed_sources }}
        nuget_interactive: ${{ inputs.nuget_interactive }}
        nuget_packages_dir: ${{ inputs.nuget_packages_dir }}
        nuget_no_cache: ${{ inputs.nuget_no_cache }}
        restore: ${{ inputs.dotnet_restore }}
        build: ${{ inputs.dotnet_build }}
        test: ${{ inputs.dotnet_test }}
        publish: ${{ inputs.dotnet_publish }}
        configuration: ${{ inputs.dotnet_configuration }}
        framework: ${{ inputs.dotnet_framework }}
        runtime: ${{ inputs.dotnet_runtime }}
        self_contained: ${{ inputs.dotnet_self_contained }}
        verbosity: ${{ inputs.dotnet_verbosity }}
        nologo: ${{ inputs.dotnet_nologo }}
        disable_parallel: ${{ inputs.dotnet_disable_parallel }}
        msbuild_targets: ${{ inputs.dotnet_msbuild_targets }}
        msbuild_properties: ${{ inputs.dotnet_msbuild_properties }}
        publish_single_file: ${{ inputs.dotnet_publish_single_file }}
        publish_trimmed: ${{ inputs.dotnet_publish_trimmed }}
        publish_ready_to_run: ${{ inputs.dotnet_publish_ready_to_run }}
        restore_args: ${{ inputs.dotnet_restore_args }}
        build_args: ${{ inputs.dotnet_build_args }}
        test_args: ${{ inputs.dotnet_test_args }}
        publish_args: ${{ inputs.dotnet_publish_args }}
        publish_dir: ${{ inputs.dotnet_publish_dir }}
        publish_multi: ${{ inputs.dotnet_publish_multi }}
        projects: ${{ inputs.dotnet_projects }}
        projects_include: ${{ inputs.dotnet_projects_include }}
        projects_exclude: ${{ inputs.dotnet_projects_exclude }}

    - name: Resolve include paths
      id: include
      if: inputs.language == 'dotnet'
      uses: ./internal/resolve-fallback
      with:
        preferred: ${{ inputs.package_paths }}
        fallback: ${{ steps.dotnet.outputs.package_paths_default }}

    - name: Resolve output zip path
      id: out
      if: inputs.language == 'dotnet'
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'

        $file = ('${{ inputs.output_zip }}' ?? '').Trim()
        if ([string]::IsNullOrWhiteSpace($file)) { $file = 'app.zip' }

        $fileName = [System.IO.Path]::GetFileName($file)
        if ([string]::IsNullOrWhiteSpace($fileName)) { throw "output_zip invalido: '$file'" }

        $zipPath = Join-Path 'veracode' $fileName
        $zipPath = $zipPath.Replace('\\','/')
        "zip_path=$zipPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Package zip
      id: package
      if: inputs.language == 'dotnet'
      uses: ./internal/package-zip
      with:
        working_directory: ${{ inputs.working_directory }}
        output_zip: ${{ steps.out.outputs.zip_path }}
        include_paths: ${{ steps.include.outputs.value }}
        exclude_paths: ${{ inputs.exclude_paths }}
        fail_on_empty_zip: ${{ inputs.fail_on_empty_zip }}

    - name: Upload artifact
      if: inputs.language == 'dotnet'
      uses: actions/upload-artifact@v4
      with:
        name: veracode-package
        path: ${{ steps.package.outputs.zip_path }}
        if-no-files-found: error
