name: build-and-package (dotnet nuget private feed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          language: dotnet
          dotnet_version: 8.0.x
          dotnet_project: MySolution.sln
          enable_nuget: "true"
          nuget_auth_mode: dotnet
          nuget_sources_json: |
            [
              {"name":"private","url":"https://example.com/nuget/v3/index.json","username":"token","password":"${{ secrets.NUGET_TOKEN }}"}
            ]
          dotnet_publish: "true"
          dotnet_publish_multi: "true"
          dotnet_configuration: Release
          dotnet_publish_dir: publish
          output_dir: veracode
          output_zip: app.zip
          artifact_name: veracode-package
