name: build-and-package (dotnet multi-project sln)

on:
  workflow_dispatch:
    inputs:
      solution_file:
        description: "Caminho do .sln (relativo ao repo)."
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          language: dotnet
          dotnet_version: 8.0.x
          dotnet_project: ${{ github.event.inputs.solution_file }}
          dotnet_publish_multi: "true"
          dotnet_configuration: Release
          dotnet_publish_dir: publish
          output_dir: veracode
          output_zip: app.zip
          artifact_name: veracode-package
