name: build-and-package (dotnet multi-project sln)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          language: dotnet
          dotnet_version: 8.0.x
          dotnet_project: MySolution.sln
          dotnet_publish_multi: "true"
          dotnet_configuration: Release
          dotnet_publish_dir: publish
          output_zip: app.zip

